import Avatar1 from "../assets/Avatar/Ellipse 50.png";
import Avatar2 from "../assets/Avatar/Ellipse 51.png";

const dummyData = [
  {
    employee_id: 1,
    email: "john@example.com",
    first_name: "John",
    last_name: "Doe",
    contact_no: "+1234567890",
    cnic: "123456789",
    designation: "Software Engineer",
    address: "123 Main Street, Cityville, State, Country",
    line_manager_id: null,
    is_line_manager: false,
  },
  {
    employee_id: 2,
    email: "jane@example.com",
    first_name: "Jane",
    last_name: "Smith",
    contact_no: "+9876543210",
    cnic: "987654321",
    designation: "Product Manager",
    address: "456 Elm Avenue, Townsville, State, Country",
    line_manager_id: null,
    is_line_manager: true,
  },
  {
    employee_id: 3,
    email: "jonas@example.com",
    first_name: "Jonas",
    last_name: "Craig",
    contact_no: "+9873654310",
    cnic: "987654123",
    designation: "Data Scientist",
    address: "789 Oak Road, Villagetown, State, Country",
    line_manager_id: 2,
    is_line_manager: false,
  },
  {
    employee_id: 4,
    email: "eve@example.com",
    first_name: "Eve",
    last_name: "Jones",
    contact_no: "+3333333333",
    cnic: "333333333",
    designation: "Data Science Lead",
    address: "111 Pine Street, Cityville, State, Country",
    line_manager_id: null,
    is_line_manager: true,
  },
  {
    employee_id: 5,
    email: "sarah@example.com",
    first_name: "Sarah",
    last_name: "Jack",
    contact_no: "+3333333333",
    cnic: "333333333",
    designation: "Software Engineer",
    address: "155 Pine Street, Cityville, State, Country",
    line_manager_id: null,
    is_line_manager: false,
  },
  {
    employee_id: 8,
    email: "emma.smith@example.com",
    first_name: "Emma",
    last_name: "Smith",
    contact_no: "+5555555555",
    cnic: "555555555",
    designation: "UX Designer",
    address: "456 Maple Lane, Villagetown, State, Country",
    line_manager_id: null,
    is_line_manager: false,
  },
  {
    employee_id: 9,
    email: "michael.jones@example.com",
    first_name: "Michael",
    last_name: "Jones",
    contact_no: "+6666666666",
    cnic: "666666666",
    designation: "Data Scientist",
    address: "123 Elm Street, Hamletsville, State, Country",
    line_manager_id: null,
    is_line_manager: false,
  },
];
export default dummyData;

export const lineManagerData = [
  {
    line_manager_id: 2,
    first_name: "Jane",
    last_name: "Smith",
    email: "jane@example.com",
    address: "456 Elm Avenue, Townsville, State, Country",
    contact_no: "+9876543210",
    cnic: "987654321",
    designation: "Product Manager",
    employee_ids: [3], // Assigning John (employee_id: 1) and Jonas (employee_id: 3) to Jane
  },
  {
    line_manager_id: 4,
    first_name: "Eve",
    last_name: "Jones",
    email: "eve@example.com",
    address: "456 Elm Avenue, Townsville, State, Country",
    contact_no: "+3333333333",
    cnic: "333333333",
    designation: "Data Science Lead",
    employee_ids: [], // Assigning Eve (employee_id: 4) as a line manager of Jonas (employee_id: 3)
  },
];

export const project = [
  {
    id: 1,
    name: "Website Redesign",
    start_date: "2023-08-01",
    end_date: "2023-09-15",
    duration: 45,
    description: "Redesign company website for better user experience.",
    status: "In Progress",
    no_of_resources: 3,
    resource_list: [1, 2, 6],
  },
  {
    id: 2,
    name: "Product Launch",
    start_date: "2023-09-01",
    end_date: "2023-10-15",
    duration: 45,
    description: "Plan and execute the launch of new product XYZ.",
    status: "Planned",
    no_of_resources: 3,
    resource_list: [3, 4, 5],
  },
  {
    id: 3,
    name: "Data Migration",
    start_date: "2023-07-15",
    end_date: "2023-08-10",
    duration: 26,
    description: "Migrate data from legacy system to new database.",
    status: "Completed",
    no_of_resources: 3,
    resource_list: [2, 3, 4],
  },
  {
    id: 4,
    name: "Conference Preparation",
    start_date: "2023-10-01",
    end_date: "2023-11-10",
    duration: 41,
    description: "Organize annual industry conference.",
    status: "Planned",
    no_of_resources: 6,
    resource_list: [2, 4, 1, 3, 5, 2],
  },
  {
    id: 5,
    name: "Mobile App Development",
    start_date: "2023-06-01",
    end_date: "2023-12-31",
    duration: 214,
    description: "Develop a cross-platform mobile app for customer engagement.",
    status: "In Progress",
    no_of_resources: 4,
    resource_list: [1, 4, 3, 5],
  },
];
export const PieChartdata = [
  { label: "None", value: 12, color: "#5368F0" },
  { label: "Normal", value: 20, color: "#9D57D5" },
  { label: "Medium", value: 48, color: "#FEAB00" },
  { label: "High", value: 20, color: "#dd0000" },
];
export const redAlertEmployees = [
  {
    id: 1,
    name: "Jhon Doe",
    avatar: Avatar2,
    frequency: "Multiple",
    date: "13 Dec 2020",
  },
  {
    id: 2,
    name: "Matt Doe",
    avatar: Avatar1,
    frequency: "Regularly",
    date: "14 Dec 2020",
  },
  {
    id: 3,
    name: "Eve Joe",
    avatar: Avatar1,
    frequency: "Many Times",
    date: "07 Dec 2020",
  },
  {
    id: 4,
    name: "Will Smith",
    avatar: Avatar2,
    frequency: "Seldom",
    date: "06 Dec 2020",
  },
];

export const designations = [
  "Software Engineer",
  "Senior Software Engineer",
  "Lead Software Engineer",
  "Software Architect",
  "Front-end Developer",
  "Back-end Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Lead Devops Engineer",
  "Quality Assurance Engineer",
  "Lead Quality Assurance Engineer",
  "UI Designer",
  "UX Designer",
  "Product Manager",
  "Project Manager",
  "Data Scientist",
  "Data Engineer",
];
